/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]

/*

use core_foundation_sys::*;
use core_foundation_sys::url::*;

#[derive(Copy, Clone)]
#[repr(i32)]
pub enum Enum_Unnamed_Services1 {
    kMIDIInvalidClient = -10830,
    kMIDIInvalidPort = -10831,
    kMIDIWrongEndpointType = -10832,
    kMIDINoConnection = -10833,
    kMIDIUnknownEndpoint = -10834,
    kMIDIUnknownProperty = -10835,
    kMIDIWrongPropertyType = -10836,
    kMIDINoCurrentSetup = -10837,
    kMIDIMessageSendErr = -10838,
    kMIDIServerStartErr = -10839,
    kMIDISetupFormatErr = -10840,
    kMIDIWrongThread = -10841,
    kMIDIObjectNotFound = -10842,
    kMIDIIDNotUnique = -10843,
    kMIDINotPermitted = -10844,
}
pub type MIDIObjectRef = UInt32;
pub type MIDIClientRef = MIDIObjectRef;
pub type MIDIPortRef = MIDIObjectRef;
pub type MIDIDeviceRef = MIDIObjectRef;
pub type MIDIEntityRef = MIDIObjectRef;
pub type MIDIEndpointRef = MIDIObjectRef;
pub type MIDITimeStamp = UInt64;
pub type MIDIObjectType = SInt32;
#[derive(Copy, Clone)]
#[repr(i32)]
pub enum Enum_Unnamed_Services2 {
    kMIDIObjectType_Other = -1,
    kMIDIObjectType_Device = 0,
    kMIDIObjectType_Entity = 1,
    kMIDIObjectType_Source = 2,
    kMIDIObjectType_Destination = 3,
    kMIDIObjectType_ExternalDevice = 16,
    kMIDIObjectType_ExternalEntity = 17,
    kMIDIObjectType_ExternalSource = 18,
    kMIDIObjectType_ExternalDestination = 19,
}
pub type MIDIUniqueID = SInt32;
#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed_Services3 { kMIDIInvalidUniqueID = 0, }
pub type MIDINotifyProc =
    ::std::option::Option<unsafe extern "C" fn(message:
                                                   *const MIDINotification,
                                               refCon:
                                                   *mut ::std::os::raw::c_void)>;
pub type MIDINotifyBlock =
    ::std::option::Option<unsafe extern "C" fn(message:
                                                   *const MIDINotification)>;
pub type MIDIReadProc =
    ::std::option::Option<unsafe extern "C" fn(pktlist: *const MIDIPacketList,
                                               readProcRefCon:
                                                   *mut ::std::os::raw::c_void,
                                               srcConnRefCon:
                                                   *mut ::std::os::raw::c_void)>;
pub type MIDIReadBlock =
    ::std::option::Option<unsafe extern "C" fn(pktlist: *const MIDIPacketList,
                                               srcConnRefCon:
                                                   *mut ::std::os::raw::c_void)>;
pub type MIDICompletionProc =
    ::std::option::Option<unsafe extern "C" fn(request:
                                                   *mut MIDISysexSendRequest)>;
#[repr(C)]
#[derive(Copy)]
pub struct MIDIPacket {
    pub timeStamp: MIDITimeStamp,
    pub length: UInt16,
    pub data: [Byte; 1usize],
}
impl ::std::clone::Clone for MIDIPacket {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for MIDIPacket {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MIDIPacketList {
    pub numPackets: UInt32,
    pub packet: [MIDIPacket; 1usize],
}
impl ::std::default::Default for MIDIPacketList {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MIDISysexSendRequest {
    pub destination: MIDIEndpointRef,
    pub data: *const Byte,
    pub bytesToSend: UInt32,
    pub complete: Boolean,
    pub reserved: [Byte; 3usize],
    pub completionProc: MIDICompletionProc,
    pub completionRefCon: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for MIDISysexSendRequest {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type MIDINotificationMessageID = SInt32;
#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed_Services4 {
    kMIDIMsgSetupChanged = 1,
    kMIDIMsgObjectAdded = 2,
    kMIDIMsgObjectRemoved = 3,
    kMIDIMsgPropertyChanged = 4,
    kMIDIMsgThruConnectionsChanged = 5,
    kMIDIMsgSerialPortOwnerChanged = 6,
    kMIDIMsgIOError = 7,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MIDINotification {
    pub messageID: MIDINotificationMessageID,
    pub messageSize: UInt32,
}
impl ::std::default::Default for MIDINotification {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MIDIObjectAddRemoveNotification {
    pub messageID: MIDINotificationMessageID,
    pub messageSize: UInt32,
    pub parent: MIDIObjectRef,
    pub parentType: MIDIObjectType,
    pub child: MIDIObjectRef,
    pub childType: MIDIObjectType,
}
impl ::std::default::Default for MIDIObjectAddRemoveNotification {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MIDIObjectPropertyChangeNotification {
    pub messageID: MIDINotificationMessageID,
    pub messageSize: UInt32,
    pub object: MIDIObjectRef,
    pub objectType: MIDIObjectType,
    pub propertyName: CFStringRef,
}
impl ::std::default::Default for MIDIObjectPropertyChangeNotification {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MIDIIOErrorNotification {
    pub messageID: MIDINotificationMessageID,
    pub messageSize: UInt32,
    pub driverDevice: MIDIDeviceRef,
    pub errorCode: OSStatus,
}
impl ::std::default::Default for MIDIIOErrorNotification {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[link(name = "CoreMIDI", kind = "framework")]
extern "C" {
    pub static kMIDIPropertyName: CFStringRef;
    pub static kMIDIPropertyManufacturer: CFStringRef;
    pub static kMIDIPropertyModel: CFStringRef;
    pub static kMIDIPropertyUniqueID: CFStringRef;
    pub static kMIDIPropertyDeviceID: CFStringRef;
    pub static kMIDIPropertyReceiveChannels: CFStringRef;
    pub static kMIDIPropertyTransmitChannels: CFStringRef;
    pub static kMIDIPropertyMaxSysExSpeed: CFStringRef;
    pub static kMIDIPropertyAdvanceScheduleTimeMuSec: CFStringRef;
    pub static kMIDIPropertyIsEmbeddedEntity: CFStringRef;
    pub static kMIDIPropertyIsBroadcast: CFStringRef;
    pub static kMIDIPropertySingleRealtimeEntity: CFStringRef;
    pub static kMIDIPropertyConnectionUniqueID: CFStringRef;
    pub static kMIDIPropertyOffline: CFStringRef;
    pub static kMIDIPropertyPrivate: CFStringRef;
    pub static kMIDIPropertyDriverOwner: CFStringRef;
    pub static kMIDIPropertyFactoryPatchNameFile: CFStringRef;
    pub static kMIDIPropertyUserPatchNameFile: CFStringRef;
    pub static kMIDIPropertyNameConfiguration: CFStringRef;
    pub static kMIDIPropertyImage: CFStringRef;
    pub static kMIDIPropertyDriverVersion: CFStringRef;
    pub static kMIDIPropertySupportsGeneralMIDI: CFStringRef;
    pub static kMIDIPropertySupportsMMC: CFStringRef;
    pub static kMIDIPropertyCanRoute: CFStringRef;
    pub static kMIDIPropertyReceivesClock: CFStringRef;
    pub static kMIDIPropertyReceivesMTC: CFStringRef;
    pub static kMIDIPropertyReceivesNotes: CFStringRef;
    pub static kMIDIPropertyReceivesProgramChanges: CFStringRef;
    pub static kMIDIPropertyReceivesBankSelectMSB: CFStringRef;
    pub static kMIDIPropertyReceivesBankSelectLSB: CFStringRef;
    pub static kMIDIPropertyTransmitsClock: CFStringRef;
    pub static kMIDIPropertyTransmitsMTC: CFStringRef;
    pub static kMIDIPropertyTransmitsNotes: CFStringRef;
    pub static kMIDIPropertyTransmitsProgramChanges: CFStringRef;
    pub static kMIDIPropertyTransmitsBankSelectMSB: CFStringRef;
    pub static kMIDIPropertyTransmitsBankSelectLSB: CFStringRef;
    pub static kMIDIPropertyPanDisruptsStereo: CFStringRef;
    pub static kMIDIPropertyIsSampler: CFStringRef;
    pub static kMIDIPropertyIsDrumMachine: CFStringRef;
    pub static kMIDIPropertyIsMixer: CFStringRef;
    pub static kMIDIPropertyIsEffectUnit: CFStringRef;
    pub static kMIDIPropertyMaxReceiveChannels: CFStringRef;
    pub static kMIDIPropertyMaxTransmitChannels: CFStringRef;
    pub static kMIDIPropertyDriverDeviceEditorApp: CFStringRef;
    pub static kMIDIPropertySupportsShowControl: CFStringRef;
    pub static kMIDIPropertyDisplayName: CFStringRef;
}
#[link(name = "CoreMIDI", kind = "framework")]
extern "C" {
    pub fn MIDIClientCreate(name: CFStringRef, notifyProc: MIDINotifyProc,
                            notifyRefCon: *mut ::std::os::raw::c_void,
                            outClient: *mut MIDIClientRef) -> OSStatus;
    pub fn MIDIClientCreateWithBlock(name: CFStringRef,
                                     outClient: *mut MIDIClientRef,
                                     notifyBlock: MIDINotifyBlock)
     -> OSStatus;
    pub fn MIDIClientDispose(client: MIDIClientRef) -> OSStatus;
    pub fn MIDIInputPortCreate(client: MIDIClientRef, portName: CFStringRef,
                               readProc: MIDIReadProc,
                               refCon: *mut ::std::os::raw::c_void,
                               outPort: *mut MIDIPortRef) -> OSStatus;
    pub fn MIDIInputPortCreateWithBlock(client: MIDIClientRef,
                                        portName: CFStringRef,
                                        outPort: *mut MIDIPortRef,
                                        readBlock: MIDIReadBlock) -> OSStatus;
    pub fn MIDIOutputPortCreate(client: MIDIClientRef, portName: CFStringRef,
                                outPort: *mut MIDIPortRef) -> OSStatus;
    pub fn MIDIPortDispose(port: MIDIPortRef) -> OSStatus;
    pub fn MIDIPortConnectSource(port: MIDIPortRef, source: MIDIEndpointRef,
                                 connRefCon: *mut ::std::os::raw::c_void)
     -> OSStatus;
    pub fn MIDIPortDisconnectSource(port: MIDIPortRef,
                                    source: MIDIEndpointRef) -> OSStatus;
    pub fn MIDIGetNumberOfDevices() -> ItemCount;
    pub fn MIDIGetDevice(deviceIndex0: ItemCount) -> MIDIDeviceRef;
    pub fn MIDIDeviceGetNumberOfEntities(device: MIDIDeviceRef) -> ItemCount;
    pub fn MIDIDeviceGetEntity(device: MIDIDeviceRef, entityIndex0: ItemCount)
     -> MIDIEntityRef;
    pub fn MIDIEntityGetNumberOfSources(entity: MIDIEntityRef) -> ItemCount;
    pub fn MIDIEntityGetSource(entity: MIDIEntityRef, sourceIndex0: ItemCount)
     -> MIDIEndpointRef;
    pub fn MIDIEntityGetNumberOfDestinations(entity: MIDIEntityRef)
     -> ItemCount;
    pub fn MIDIEntityGetDestination(entity: MIDIEntityRef,
                                    destIndex0: ItemCount) -> MIDIEndpointRef;
    pub fn MIDIEntityGetDevice(inEntity: MIDIEntityRef,
                               outDevice: *mut MIDIDeviceRef) -> OSStatus;
    pub fn MIDIGetNumberOfSources() -> ItemCount;
    pub fn MIDIGetSource(sourceIndex0: ItemCount) -> MIDIEndpointRef;
    pub fn MIDIGetNumberOfDestinations() -> ItemCount;
    pub fn MIDIGetDestination(destIndex0: ItemCount) -> MIDIEndpointRef;
    pub fn MIDIEndpointGetEntity(inEndpoint: MIDIEndpointRef,
                                 outEntity: *mut MIDIEntityRef) -> OSStatus;
    pub fn MIDIDestinationCreate(client: MIDIClientRef, name: CFStringRef,
                                 readProc: MIDIReadProc,
                                 refCon: *mut ::std::os::raw::c_void,
                                 outDest: *mut MIDIEndpointRef) -> OSStatus;
    pub fn MIDIDestinationCreateWithBlock(client: MIDIClientRef,
                                          name: CFStringRef,
                                          outDest: *mut MIDIEndpointRef,
                                          readBlock: MIDIReadBlock)
     -> OSStatus;
    pub fn MIDISourceCreate(client: MIDIClientRef, name: CFStringRef,
                            outSrc: *mut MIDIEndpointRef) -> OSStatus;
    pub fn MIDIEndpointDispose(endpt: MIDIEndpointRef) -> OSStatus;
    pub fn MIDIGetNumberOfExternalDevices() -> ItemCount;
    pub fn MIDIGetExternalDevice(deviceIndex0: ItemCount) -> MIDIDeviceRef;
    pub fn MIDIObjectGetIntegerProperty(obj: MIDIObjectRef,
                                        propertyID: CFStringRef,
                                        outValue: *mut SInt32) -> OSStatus;
    pub fn MIDIObjectSetIntegerProperty(obj: MIDIObjectRef,
                                        propertyID: CFStringRef,
                                        value: SInt32) -> OSStatus;
    pub fn MIDIObjectGetStringProperty(obj: MIDIObjectRef,
                                       propertyID: CFStringRef,
                                       str: *mut CFStringRef) -> OSStatus;
    pub fn MIDIObjectSetStringProperty(obj: MIDIObjectRef,
                                       propertyID: CFStringRef,
                                       str: CFStringRef) -> OSStatus;
    pub fn MIDIObjectGetDataProperty(obj: MIDIObjectRef,
                                     propertyID: CFStringRef,
                                     outData: *mut CFDataRef) -> OSStatus;
    pub fn MIDIObjectSetDataProperty(obj: MIDIObjectRef,
                                     propertyID: CFStringRef, data: CFDataRef)
     -> OSStatus;
    pub fn MIDIObjectGetDictionaryProperty(obj: MIDIObjectRef,
                                           propertyID: CFStringRef,
                                           outDict: *mut CFDictionaryRef)
     -> OSStatus;
    pub fn MIDIObjectSetDictionaryProperty(obj: MIDIObjectRef,
                                           propertyID: CFStringRef,
                                           dict: CFDictionaryRef) -> OSStatus;
    pub fn MIDIObjectGetProperties(obj: MIDIObjectRef,
                                   outProperties: *mut CFPropertyListRef,
                                   deep: Boolean) -> OSStatus;
    pub fn MIDIObjectRemoveProperty(obj: MIDIObjectRef,
                                    propertyID: CFStringRef) -> OSStatus;
    pub fn MIDIObjectFindByUniqueID(inUniqueID: MIDIUniqueID,
                                    outObject: *mut MIDIObjectRef,
                                    outObjectType: *mut MIDIObjectType)
     -> OSStatus;
    pub fn MIDISend(port: MIDIPortRef, dest: MIDIEndpointRef,
                    pktlist: *const MIDIPacketList) -> OSStatus;
    pub fn MIDISendSysex(request: *mut MIDISysexSendRequest) -> OSStatus;
    pub fn MIDIReceived(src: MIDIEndpointRef, pktlist: *const MIDIPacketList)
     -> OSStatus;
    pub fn MIDIFlushOutput(dest: MIDIEndpointRef) -> OSStatus;
    pub fn MIDIRestart() -> OSStatus;
    pub fn MIDIPacketListInit(pktlist: *mut MIDIPacketList)
     -> *mut MIDIPacket;
    pub fn MIDIPacketListAdd(pktlist: *mut MIDIPacketList,
                             listSize: ByteCount, curPacket: *mut MIDIPacket,
                             time: MIDITimeStamp, nData: ByteCount,
                             data: *const Byte) -> *mut MIDIPacket;
}

*/
